language: "en_US"
custom_command: "classicape"
storage_mode: "file"

#storage_mode: "mysql"
#database_credentials:
#  host: "localhost"
#  port: 3306
#  name: "classicape"
#  user: "root"
#  password: "root"


